### ISSUE TITLE
BUG: footnotes in README.md don't exist

### ISSUE THREAD

**Issue by pcmoore** [seccomp/containers-golang#1]
The current README.md has markers for at least three different footnotes, but the links aren't provided.  I suspect this is a copy-n-paste typo so it shouldn't be too hard to get the links from the original source material.

**Comment by rhatdan** [comment]
Fixed in latest release.

**Comment by pcmoore** [comment]
I don't see the fixes; maybe you forgot to push your local changes?

* https://github.com/seccomp/containers-golang/blob/master/README.md

**Comment by pcmoore** [comment]
Looks better now, thanks.

**Comment by rhatdan** [comment]
If you got a better description of seccomp, I am all ears.  I will soon start playing the PR Review process, after I announce the repo.

**Comment by pcmoore** [comment]
I think it's fine.  FWIW, the best I could come up with for libseccomp is below:

* https://github.com/seccomp/libseccomp/blob/master/README.md
